import { jsPDF } from 'jspdf'

const BRAND = 'MediCare+'
const PRIMARY: [number, number, number] = [13, 138, 124] // matches --primary-500

function addHeader(doc: jsPDF, title: string) {
  doc.setFillColor(...PRIMARY)
  doc.rect(0, 0, 210, 28, 'F')
  doc.setTextColor(255, 255, 255)
  doc.setFontSize(18)
  doc.setFont('helvetica', 'bold')
  doc.text(BRAND, 14, 17)
  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  doc.text('Your Health Hub', 14, 23)
  doc.setFontSize(13)
  doc.text(title, 196, 17, { align: 'right' })
  doc.setTextColor(0, 0, 0)
}

function addFooter(doc: jsPDF) {
  const pageHeight = doc.internal.pageSize.getHeight()
  doc.setFontSize(8)
  doc.setTextColor(120, 120, 120)
  doc.text(
    'Generated by MediCare+ — for demonstration purposes only, not a substitute for professional medical advice.',
    105,
    pageHeight - 10,
    { align: 'center' },
  )
  doc.setTextColor(0, 0, 0)
}

function labelValue(doc: jsPDF, x: number, y: number, label: string, value: string) {
  doc.setFontSize(9)
  doc.setTextColor(120, 120, 120)
  doc.text(label, x, y)
  doc.setFontSize(11)
  doc.setTextColor(20, 20, 20)
  doc.text(value || '-', x, y + 6)
}

export interface PrescriptionPdfInput {
  doctorName: string
  patientName: string
  date: string
  timeSlot: string
  symptoms?: string | null
  prescription: string
  followUp?: boolean
}

export function downloadPrescriptionPdf(data: PrescriptionPdfInput) {
  const doc = new jsPDF()
  addHeader(doc, 'Prescription')

  labelValue(doc, 14, 45, 'PATIENT', data.patientName)
  labelValue(doc, 110, 45, 'DOCTOR', data.doctorName)
  labelValue(doc, 14, 62, 'DATE', data.date)
  labelValue(doc, 110, 62, 'TIME SLOT', data.timeSlot)

  doc.setDrawColor(220, 220, 220)
  doc.line(14, 72, 196, 72)

  let y = 84
  if (data.symptoms) {
    doc.setFontSize(9)
    doc.setTextColor(120, 120, 120)
    doc.text('SYMPTOMS REPORTED', 14, y)
    doc.setFontSize(11)
    doc.setTextColor(20, 20, 20)
    const symptomLines = doc.splitTextToSize(data.symptoms, 180)
    doc.text(symptomLines, 14, y + 7)
    y += 7 + symptomLines.length * 6 + 10
  }

  doc.setFontSize(9)
  doc.setTextColor(120, 120, 120)
  doc.text('PRESCRIPTION / NOTES', 14, y)
  doc.setFontSize(12)
  doc.setTextColor(20, 20, 20)
  const rxLines = doc.splitTextToSize(data.prescription, 180)
  doc.text(rxLines, 14, y + 8)
  y += 8 + rxLines.length * 7 + 10

  if (data.followUp) {
    doc.setFontSize(10)
    doc.setTextColor(13, 138, 124)
    doc.text('A follow-up consultation has been recommended.', 14, y)
  }

  addFooter(doc)
  doc.save(`Prescription_${data.patientName.replace(/\s+/g, '_')}_${data.date}.pdf`)
}

export interface InvoiceItem {
  name: string
  quantity?: number
  price: number
  brand?: string
}

export interface InvoicePdfInput {
  invoiceNumber: string
  date: string
  billedTo: string
  items: InvoiceItem[]
  total: number
  paymentMethod: string
  status: string
  address?: string | null
}

export function downloadInvoicePdf(data: InvoicePdfInput) {
  const doc = new jsPDF()
  addHeader(doc, 'Invoice')

  labelValue(doc, 14, 45, 'INVOICE NO.', data.invoiceNumber)
  labelValue(doc, 110, 45, 'DATE', data.date)
  labelValue(doc, 14, 62, 'BILLED TO', data.billedTo)
  labelValue(doc, 110, 62, 'PAYMENT METHOD', data.paymentMethod.toUpperCase())
  if (data.address) {
    doc.setFontSize(9)
    doc.setTextColor(120, 120, 120)
    doc.text('ADDRESS', 14, 76)
    doc.setFontSize(10)
    doc.setTextColor(20, 20, 20)
    doc.text(doc.splitTextToSize(data.address, 180), 14, 82)
  }

  let y = data.address ? 96 : 78
  doc.setDrawColor(220, 220, 220)
  doc.line(14, y, 196, y)
  y += 8

  doc.setFontSize(9)
  doc.setTextColor(120, 120, 120)
  doc.text('ITEM', 14, y)
  doc.text('QTY', 130, y, { align: 'right' })
  doc.text('PRICE', 160, y, { align: 'right' })
  doc.text('AMOUNT', 196, y, { align: 'right' })
  y += 4
  doc.line(14, y, 196, y)
  y += 8

  doc.setTextColor(20, 20, 20)
  for (const item of data.items) {
    const qty = item.quantity ?? 1
    doc.setFontSize(10)
    const nameLines = doc.splitTextToSize(item.brand ? `${item.name} (${item.brand})` : item.name, 100)
    doc.text(nameLines, 14, y)
    doc.text(String(qty), 130, y, { align: 'right' })
    doc.text(`Rs ${item.price}`, 160, y, { align: 'right' })
    doc.text(`Rs ${item.price * qty}`, 196, y, { align: 'right' })
    y += Math.max(7, nameLines.length * 6)
  }

  y += 4
  doc.line(120, y, 196, y)
  y += 8
  doc.setFontSize(12)
  doc.setFont('helvetica', 'bold')
  doc.text('TOTAL', 160, y, { align: 'right' })
  doc.text(`Rs ${data.total}`, 196, y, { align: 'right' })
  doc.setFont('helvetica', 'normal')

  y += 14
  doc.setFontSize(10)
  doc.setTextColor(13, 138, 124)
  doc.text(`Status: ${data.status}`, 14, y)

  addFooter(doc)
  doc.save(`Invoice_${data.invoiceNumber}.pdf`)
}
